import type { Establishment } from "@/types";

export const DEMO_ESTABLISHMENTS: Establishment[] = [
  {
    id: "demo-1",
    place_id: "demo-place-1",
    name: "Reunion Island Coffee",
    address: "136 Ossington Ave, Toronto, ON M6J 2Z5",
    lat: 43.6465,
    lng: -79.4246,
    type: "cafe",
    hours: {
      open_now: true,
      weekday_text: [
        "Monday: 7:00 AM – 6:00 PM",
        "Tuesday: 7:00 AM – 6:00 PM",
        "Wednesday: 7:00 AM – 6:00 PM",
        "Thursday: 7:00 AM – 6:00 PM",
        "Friday: 7:00 AM – 6:00 PM",
        "Saturday: 8:00 AM – 6:00 PM",
        "Sunday: 8:00 AM – 5:00 PM",
      ],
    },
    phone: "+1 416-588-0374",
    website: "https://reunionislandcoffee.com",
    google_rating: 4.7,
    google_data_json: null,
    features: {
      step_free_entrance: {
        id: "demo-f1a",
        establishment_id: "demo-1",
        feature_type: "step_free_entrance",
        value: "yes",
        status: "confirmed",
        report_count: 4,
        yes_count: 4,
        no_count: 0,
      },
      accessible_bathroom: {
        id: "demo-f1b",
        establishment_id: "demo-1",
        feature_type: "accessible_bathroom",
        value: "yes",
        status: "confirmed",
        report_count: 3,
        yes_count: 3,
        no_count: 0,
      },
      change_table: {
        id: "demo-f1c",
        establishment_id: "demo-1",
        feature_type: "change_table",
        value: "no",
        status: "confirmed",
        report_count: 2,
        yes_count: 0,
        no_count: 2,
      },
      high_chairs: { id: "demo-f1d", establishment_id: "demo-1", feature_type: "high_chairs", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
      auto_door_opener: { id: "demo-f1e", establishment_id: "demo-1", feature_type: "auto_door_opener", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
      stroller_friendly_layout: { id: "demo-f1f", establishment_id: "demo-1", feature_type: "stroller_friendly_layout", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
      booster_seats: { id: "demo-f1g", establishment_id: "demo-1", feature_type: "booster_seats", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
      change_table_mens: { id: "demo-f1h", establishment_id: "demo-1", feature_type: "change_table_mens", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
      change_table_family: { id: "demo-f1i", establishment_id: "demo-1", feature_type: "change_table_family", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
    },
    distance_meters: 180,
  },
  {
    id: "demo-2",
    place_id: "demo-place-2",
    name: "The Roncesvalles Café",
    address: "205 Roncesvalles Ave, Toronto, ON M6R 2L5",
    lat: 43.6441,
    lng: -79.4494,
    type: "cafe",
    hours: {
      open_now: true,
      weekday_text: [
        "Monday: 8:00 AM – 5:00 PM",
        "Tuesday: 8:00 AM – 5:00 PM",
        "Wednesday: 8:00 AM – 5:00 PM",
        "Thursday: 8:00 AM – 5:00 PM",
        "Friday: 8:00 AM – 5:00 PM",
        "Saturday: 8:00 AM – 5:00 PM",
        "Sunday: 9:00 AM – 4:00 PM",
      ],
    },
    phone: "+1 416-535-0404",
    website: "https://roncesvallescafe.ca",
    google_rating: 4.4,
    google_data_json: null,
    features: {
      step_free_entrance: {
        id: "demo-f2a",
        establishment_id: "demo-2",
        feature_type: "step_free_entrance",
        value: "yes",
        status: "confirmed",
        report_count: 3,
        yes_count: 3,
        no_count: 0,
      },
      accessible_bathroom: {
        id: "demo-f2b",
        establishment_id: "demo-2",
        feature_type: "accessible_bathroom",
        value: null,
        status: "reported",
        report_count: 1,
        yes_count: 1,
        no_count: 0,
      },
      change_table: {
        id: "demo-f2c",
        establishment_id: "demo-2",
        feature_type: "change_table",
        value: "yes",
        status: "confirmed",
        report_count: 2,
        yes_count: 2,
        no_count: 0,
      },
      high_chairs: { id: "demo-f2d", establishment_id: "demo-2", feature_type: "high_chairs", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
      auto_door_opener: { id: "demo-f2e", establishment_id: "demo-2", feature_type: "auto_door_opener", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
      stroller_friendly_layout: { id: "demo-f2f", establishment_id: "demo-2", feature_type: "stroller_friendly_layout", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
      booster_seats: { id: "demo-f2g", establishment_id: "demo-2", feature_type: "booster_seats", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
      change_table_mens: { id: "demo-f2h", establishment_id: "demo-2", feature_type: "change_table_mens", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
      change_table_family: { id: "demo-f2i", establishment_id: "demo-2", feature_type: "change_table_family", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
    },
    distance_meters: 420,
  },
  {
    id: "demo-3",
    place_id: "demo-place-3",
    name: "Leslieville Pumps",
    address: "891 Queen St E, Toronto, ON M4M 1J4",
    lat: 43.6586,
    lng: -79.3345,
    type: "restaurant",
    hours: {
      open_now: false,
      weekday_text: [
        "Monday: Closed",
        "Tuesday: 11:00 AM – 10:00 PM",
        "Wednesday: 11:00 AM – 10:00 PM",
        "Thursday: 11:00 AM – 10:00 PM",
        "Friday: 11:00 AM – 11:00 PM",
        "Saturday: 10:00 AM – 11:00 PM",
        "Sunday: 10:00 AM – 9:00 PM",
      ],
    },
    phone: "+1 416-465-2271",
    website: "https://leslievillepumps.com",
    google_rating: 4.3,
    google_data_json: null,
    features: {
      step_free_entrance: {
        id: "demo-f3a",
        establishment_id: "demo-3",
        feature_type: "step_free_entrance",
        value: null,
        status: "unknown",
        report_count: 0,
        yes_count: 0,
        no_count: 0,
      },
      accessible_bathroom: {
        id: "demo-f3b",
        establishment_id: "demo-3",
        feature_type: "accessible_bathroom",
        value: null,
        status: "unknown",
        report_count: 0,
        yes_count: 0,
        no_count: 0,
      },
      change_table: {
        id: "demo-f3c",
        establishment_id: "demo-3",
        feature_type: "change_table",
        value: null,
        status: "unknown",
        report_count: 0,
        yes_count: 0,
        no_count: 0,
      },
      high_chairs: { id: "demo-f3d", establishment_id: "demo-3", feature_type: "high_chairs", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
      auto_door_opener: { id: "demo-f3e", establishment_id: "demo-3", feature_type: "auto_door_opener", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
      stroller_friendly_layout: { id: "demo-f3f", establishment_id: "demo-3", feature_type: "stroller_friendly_layout", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
      booster_seats: { id: "demo-f3g", establishment_id: "demo-3", feature_type: "booster_seats", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
      change_table_mens: { id: "demo-f3h", establishment_id: "demo-3", feature_type: "change_table_mens", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
      change_table_family: { id: "demo-f3i", establishment_id: "demo-3", feature_type: "change_table_family", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
    },
    distance_meters: 750,
  },
  {
    id: "demo-4",
    place_id: "demo-place-4",
    name: "Jimmy's Coffee",
    address: "107 Portland St, Toronto, ON M5V 2N4",
    lat: 43.6456,
    lng: -79.3994,
    type: "cafe",
    hours: {
      open_now: true,
      weekday_text: [
        "Monday: 7:30 AM – 6:00 PM",
        "Tuesday: 7:30 AM – 6:00 PM",
        "Wednesday: 7:30 AM – 6:00 PM",
        "Thursday: 7:30 AM – 6:00 PM",
        "Friday: 7:30 AM – 6:00 PM",
        "Saturday: 8:00 AM – 6:00 PM",
        "Sunday: 8:00 AM – 5:00 PM",
      ],
    },
    phone: "+1 416-703-2423",
    website: "https://jimmyscoffee.ca",
    google_rating: 4.8,
    google_data_json: null,
    features: {
      step_free_entrance: {
        id: "demo-f4a",
        establishment_id: "demo-4",
        feature_type: "step_free_entrance",
        value: "no",
        status: "confirmed",
        report_count: 3,
        yes_count: 0,
        no_count: 3,
      },
      accessible_bathroom: {
        id: "demo-f4b",
        establishment_id: "demo-4",
        feature_type: "accessible_bathroom",
        value: null,
        status: "disputed",
        report_count: 2,
        yes_count: 1,
        no_count: 1,
      },
      change_table: {
        id: "demo-f4c",
        establishment_id: "demo-4",
        feature_type: "change_table",
        value: null,
        status: "unknown",
        report_count: 0,
        yes_count: 0,
        no_count: 0,
      },
      high_chairs: { id: "demo-f4d", establishment_id: "demo-4", feature_type: "high_chairs", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
      auto_door_opener: { id: "demo-f4e", establishment_id: "demo-4", feature_type: "auto_door_opener", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
      stroller_friendly_layout: { id: "demo-f4f", establishment_id: "demo-4", feature_type: "stroller_friendly_layout", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
      booster_seats: { id: "demo-f4g", establishment_id: "demo-4", feature_type: "booster_seats", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
      change_table_mens: { id: "demo-f4h", establishment_id: "demo-4", feature_type: "change_table_mens", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
      change_table_family: { id: "demo-f4i", establishment_id: "demo-4", feature_type: "change_table_family", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
    },
    distance_meters: 1100,
  },
  {
    id: "demo-5",
    place_id: "demo-place-5",
    name: "Makers Café Trinity Bellwoods",
    address: "842 Bloor St W, Toronto, ON M6G 1M3",
    lat: 43.6607,
    lng: -79.4209,
    type: "cafe",
    hours: {
      open_now: true,
      weekday_text: [
        "Monday: 7:00 AM – 7:00 PM",
        "Tuesday: 7:00 AM – 7:00 PM",
        "Wednesday: 7:00 AM – 7:00 PM",
        "Thursday: 7:00 AM – 7:00 PM",
        "Friday: 7:00 AM – 7:00 PM",
        "Saturday: 8:00 AM – 7:00 PM",
        "Sunday: 8:00 AM – 6:00 PM",
      ],
    },
    phone: "+1 416-532-0045",
    website: "https://makerscafe.ca",
    google_rating: 4.5,
    google_data_json: null,
    features: {
      step_free_entrance: {
        id: "demo-f5a",
        establishment_id: "demo-5",
        feature_type: "step_free_entrance",
        value: "yes",
        status: "confirmed",
        report_count: 5,
        yes_count: 5,
        no_count: 0,
      },
      accessible_bathroom: {
        id: "demo-f5b",
        establishment_id: "demo-5",
        feature_type: "accessible_bathroom",
        value: "yes",
        status: "confirmed",
        report_count: 4,
        yes_count: 4,
        no_count: 0,
      },
      change_table: {
        id: "demo-f5c",
        establishment_id: "demo-5",
        feature_type: "change_table",
        value: "yes",
        status: "confirmed",
        report_count: 3,
        yes_count: 3,
        no_count: 0,
      },
      high_chairs: { id: "demo-f5d", establishment_id: "demo-5", feature_type: "high_chairs", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
      auto_door_opener: { id: "demo-f5e", establishment_id: "demo-5", feature_type: "auto_door_opener", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
      stroller_friendly_layout: { id: "demo-f5f", establishment_id: "demo-5", feature_type: "stroller_friendly_layout", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
      booster_seats: { id: "demo-f5g", establishment_id: "demo-5", feature_type: "booster_seats", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
      change_table_mens: { id: "demo-f5h", establishment_id: "demo-5", feature_type: "change_table_mens", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
      change_table_family: { id: "demo-f5i", establishment_id: "demo-5", feature_type: "change_table_family", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
    },
    distance_meters: 320,
  },
  {
    id: "demo-6",
    place_id: "demo-place-6",
    name: "La Carnita Ossington",
    address: "501 College St, Toronto, ON M6G 1A5",
    lat: 43.6555,
    lng: -79.4152,
    type: "restaurant",
    hours: {
      open_now: false,
      weekday_text: [
        "Monday: Closed",
        "Tuesday: 5:00 PM – 10:00 PM",
        "Wednesday: 5:00 PM – 10:00 PM",
        "Thursday: 5:00 PM – 10:00 PM",
        "Friday: 5:00 PM – 11:00 PM",
        "Saturday: 12:00 PM – 11:00 PM",
        "Sunday: 12:00 PM – 9:00 PM",
      ],
    },
    phone: "+1 647-352-7996",
    website: "https://lacarnita.com",
    google_rating: 4.2,
    google_data_json: null,
    features: {
      step_free_entrance: {
        id: "demo-f6a",
        establishment_id: "demo-6",
        feature_type: "step_free_entrance",
        value: null,
        status: "reported",
        report_count: 1,
        yes_count: 1,
        no_count: 0,
      },
      accessible_bathroom: {
        id: "demo-f6b",
        establishment_id: "demo-6",
        feature_type: "accessible_bathroom",
        value: null,
        status: "unknown",
        report_count: 0,
        yes_count: 0,
        no_count: 0,
      },
      change_table: {
        id: "demo-f6c",
        establishment_id: "demo-6",
        feature_type: "change_table",
        value: "yes",
        status: "confirmed",
        report_count: 2,
        yes_count: 2,
        no_count: 0,
      },
      high_chairs: { id: "demo-f6d", establishment_id: "demo-6", feature_type: "high_chairs", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
      auto_door_opener: { id: "demo-f6e", establishment_id: "demo-6", feature_type: "auto_door_opener", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
      stroller_friendly_layout: { id: "demo-f6f", establishment_id: "demo-6", feature_type: "stroller_friendly_layout", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
      booster_seats: { id: "demo-f6g", establishment_id: "demo-6", feature_type: "booster_seats", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
      change_table_mens: { id: "demo-f6h", establishment_id: "demo-6", feature_type: "change_table_mens", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
      change_table_family: { id: "demo-f6i", establishment_id: "demo-6", feature_type: "change_table_family", value: null, status: "unknown", report_count: 0, yes_count: 0, no_count: 0 },
    },
    distance_meters: 560,
  },
];

// Default map center (Trinity Bellwoods area, Toronto)
export const DEMO_CENTER = { lat: 43.6529, lng: -79.4117 };

export function filterDemoEstablishments(
  establishments: Establishment[],
  type?: string
): Establishment[] {
  if (!type || type === "all") return establishments;
  return establishments.filter((e) => e.type === type);
}
